### ISSUE TITLE
README should document `make docs`

### ISSUE THREAD

**Issue by gz-c** [skycoin/libskycoin#19]
**Feature description**

Document `make docs`

**Is your feature request related to a problem? Please describe.**
No mention to `make docs` target in project README .

**Describe the solution you'd like**

- [x] List all make targets 
- [x] Add a section about Doxygen comment syntax , per the style guidelines
- [x] Mention devdocs generation in `development` section
- [x] Implement `make docs-skyapi` and integrate it with `make docs`

**Comment by stdevMac** [comment]
`make docs-swagger` it is not necessary, there is a way with swagger-ui to load the file .yml and dynamically it serves from an index.html and a bit of javascript the annotations made from swagger to all the specified enpoints.

**Comment by olemis** [comment]
We definitely need targets for this . Besides we should be using some of [standard make targets](https://www.gnu.org/prep/standards/html_node/Standard-Targets.html) rather than `make docs`.

**Comment by olemis** [comment]
the process needs to be run from command line since deliverables for release (including docs) are created in Travis builds and pushed automatically onto Gothub Releases .

**Comment by stdevMac** [comment]
in the process of `make generate-swagger-spec` i will include a operation to update docs , that is just update the swagger.yml in `docs` folder

**Comment by olemis** [comment]
`swagger.yml` is not meant to be located in docs . There should be a new `lib/swagger` folder containing two files `skycoin.swagger.<VERSION_OR_GITHASH>.{yml,json}` . We'll move forward and create in this folder other Swagger specs files for different services.

**Comment by olemis** [comment]
[Standard documentation targets](https://www.gnu.org/prep/standards/html_node/Standard-Targets.html) are not related to Swagger spec generation though . The former are meant to generate API docs (like those found in readthedocs.org, dash , zeal ) in the output formats supported by Doxygen and Swagger tools .

**Comment by stdevMac** [comment]
For each service we have to create his own api docs, generated by `swagger-ui`, i will work on that's.

**Comment by olemis** [comment]
Please finish with `skycoin/skycoin` first .

**Comment by olemis** [comment]
The scope of this issue is limited to `doxygen` (`lib/cgo`) and Swagger doc tool (`lib/swagger`).

**Comment by olemis** [comment]
fixed in 55d1e53
