### ISSUE TITLE
Lack of functions to export

### ISSUE THREAD

**Issue by stdevHan** [skycoin/libskycoin#20]
Lack of export of functions such as SKY_base58_Hex2Base58(https://github.com/skycoin/pyskycoin/blob/develop/tests/test_cipher_address.py#L20) doing as a function https://github.com/skycoin/skycoin/blob/develop/src/cipher/address_test.go#L63

**Comment by olemis** [comment]
@stdevHan @gz-c what would be the current equivalent of former `DecodeBase58Address` ?

**Comment by olemis** [comment]
fixed in `v0.25dev`

**Comment by olemis** [comment]
fixed in `v0.25dev` , see #21
