### ISSUE TITLE
Implement client for the hardware wallet daemon REST API

### ISSUE THREAD

**Issue by olemis** [skycoin/libskycoin#28]
**Feature description**

Implement client for the hardware wallet daemon REST API

**Is your feature request related to a problem? Please describe.**
skycoin/hardware-wallet-daemon#8 adds a `swagger.yml` spec defining HTTP REST API for interacting with hardware wallets .

**Describe the solution you'd like**
Generate C client powered by `libcurl`

**Describe alternatives you've considered**
There might be other choices but Skycoin nodes REST API is generated with `libcurl` already.

**Possible implementation**

- [ ] Grab the YAML OpenAPI spec from github project in `make configure`
- [ ] Move Skycoin node REST API client to `lib/curl/skycoin`
- [ ] Generate library at `lib/curl/skywallet`
- [ ] Remove intermediate output files in `make clean`

**Comment by stdevMac** [comment]
@olemis i will create the library in `lib\skyhwd` in order to keep name uniformity with other implementations of this library
