### ISSUE TITLE
Release Libskycoin 0.25.1

### ISSUE THREAD

**Issue by stdevHan** [skycoin/libskycoin#30]
- [x]  Sync `0.25.dev` and `master` branches
- [x] Create release branch `release-0.25.1`
- [x] Update release process docs
- [x] Skycoin submodule checkout at `v0.25.1`
- [x] Update `CHANGELOG.md`
- [x] Ensure `libc` and `skyapi` docs are up-to-date
- [x] PR from `release-0.25.1` to `master`
- [x] Review release PR
- [x] Tag `master` with `v0.25.1` . This will deploy binaries for different architectures to Github releases .
- [x] Add docs sync in release procedure (if missing)
- [x] Move `docker/images/circle/` => `docker/images/deploy-arm`

**Comment by olemis** [comment]
@stdevHan , the merge is from `0.25.dev` to `master`

**Comment by olemis** [comment]
fixed by 5dec78d
