### ISSUE TITLE
Refactor in tests

### ISSUE THREAD

**Issue by stdevAlDen** [skycoin/libskycoin#7]
Define an interface implemented by [check](https://github.com/libcheck/check/), [criterion](https://github.com/Snaipe/Criterion) or any other you want.
This is related to the need of use the same tests battery in [libskycoin](https://github.com/skycoin/libskycoin) and hardware [wallet](https://github.com/skycoin/hardware-wallet/tree/master/skycoin-api).

**Comment by olemis** [comment]
@stdevHan pls continue the work done for this issue .

**Comment by olemis** [comment]
fixed in 47f8d0f
